import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1759336308248 implements MigrationInterface {
    name = 'InitialSchema1759336308248'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`password_resets\` (\`id\` varchar(36) NOT NULL, \`email\` varchar(255) NOT NULL, \`otp\` varchar(6) NOT NULL, \`resetToken\` varchar(255) NULL, \`otpExpiresAt\` timestamp NOT NULL, \`tokenExpiresAt\` timestamp NULL, \`isUsed\` tinyint NOT NULL DEFAULT 0, \`attempts\` int NOT NULL DEFAULT '0', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_roles\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`permissions\` json NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_4a77d431a6b2ac981c342b13c9\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_has_roles\` (\`user_id\` varchar(255) NOT NULL, \`role_id\` int NOT NULL, \`assigned_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`user_id\`, \`role_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` varchar(36) NOT NULL, \`email\` varchar(150) NOT NULL, \`password\` varchar(255) NOT NULL, \`fullName\` varchar(200) NOT NULL, \`phone\` varchar(20) NULL, \`status\` enum ('active', 'inactive', 'suspended', 'guest') NOT NULL DEFAULT 'guest', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`reports_config\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`config\` json NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_4d0462a12befd82c5979ae17fa\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`reports\` (\`id\` int NOT NULL AUTO_INCREMENT, \`data\` json NULL, \`status\` enum ('draft', 'final', 'archived') NOT NULL DEFAULT 'draft', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`user_id\` varchar(36) NULL, \`report_config_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`payment_gateways\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`type\` enum ('mobile_money', 'card', 'bank_transfer') NOT NULL, \`slug\` enum ('OM', 'MTN', 'WAVE', 'MOOV', 'CARD', 'BANK') NULL, \`logo\` varchar(255) NULL, \`integration_config\` json NULL, \`transaction_fee_percentage\` decimal(5,2) NULL, \`transaction_fee_payer\` enum ('donor', 'parish', 'shared') NOT NULL DEFAULT 'donor', \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_d905f911f872997feb55664dd7\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`transactions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`reference\` varchar(255) NOT NULL, \`external_reference\` varchar(255) NULL, \`meta\` json NULL, \`amount\` decimal(10,2) NOT NULL, \`currency\` varchar(3) NOT NULL DEFAULT 'XOF', \`status\` enum ('pending', 'success', 'failed', 'refunded', 'cancelled') NOT NULL DEFAULT 'pending', \`transaction_type\` enum ('mass_request', 'offering', 'contribution', 'refund') NOT NULL, \`related_object_id\` int NOT NULL, \`fee_amount\` decimal(10,2) NOT NULL DEFAULT '0.00', \`net_amount\` decimal(10,2) NULL, \`failure_reason\` text NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`user_id\` varchar(36) NULL, \`payment_gateway_id\` int NULL, UNIQUE INDEX \`IDX_dd85cc865e0c3d5d4be095d3f3\` (\`reference\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`parishes\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`address\` text NULL, \`contact_email\` varchar(150) NULL, \`contact_phone\` varchar(20) NULL, \`bank_account_info\` json NULL, \`mobile_money_numbers\` json NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`idx_parish_name\` (\`name\`), UNIQUE INDEX \`IDX_0c5bb9849cf031ff303e84203b\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`offering_types\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_2ba25d9c762806798d33170e65\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`offering_campaigns\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`description\` text NOT NULL, \`target_amount\` decimal(15,2) NULL, \`start_date\` date NOT NULL, \`end_date\` date NOT NULL, \`status\` enum ('draft', 'active', 'paused', 'completed', 'cancelled') NOT NULL DEFAULT 'draft', \`image_url\` varchar(500) NULL, \`created_by_user_id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`idx_campaign_status\` (\`status\`), INDEX \`idx_campaign_dates\` (\`start_date\`, \`end_date\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`offerings\` (\`id\` int NOT NULL AUTO_INCREMENT, \`amount\` decimal(12,2) NOT NULL, \`message\` text NULL, \`status\` enum ('pending', 'completed', 'failed', 'cancelled') NOT NULL DEFAULT 'pending', \`payment_method\` enum ('cash', 'bank_transfer', 'mobile_money', 'card') NOT NULL DEFAULT 'cash', \`anonymous_donor_info\` json NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`offering_type_id\` int NULL, \`user_id\` varchar(36) NULL, \`campaign_id\` varchar(36) NULL, INDEX \`idx_offering_status\` (\`status\`), INDEX \`idx_offering_amount\` (\`amount\`), INDEX \`idx_offering_date\` (\`created_at\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`celebration_types\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_70cfa0b4b38261bd5cc6350edb\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`mass_calendar\` (\`id\` int NOT NULL AUTO_INCREMENT, \`mass_date\` date NOT NULL, \`start_time\` time NOT NULL, \`end_time\` time NOT NULL, \`location\` varchar(255) NULL, \`status\` enum ('active', 'cancelled', 'disabled_requests') NOT NULL DEFAULT 'active', \`notes\` text NULL, \`created_by_user_id\` varchar(36) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`celebration_type_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`mass_request_types\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`base_amount\` decimal(10,2) NOT NULL, \`template_details\` json NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_3819838db5da5f8c44f1304f39\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`mass_requests\` (\`id\` int NOT NULL AUTO_INCREMENT, \`requester_name\` varchar(255) NOT NULL, \`requester_phone\` varchar(20) NULL, \`requester_email\` varchar(150) NULL, \`scheduled_date\` date NULL, \`message_additionnel\` text NULL, \`status\` enum ('pending_payment', 'paid', 'scheduled', 'completed', 'cancelled', 'reported') NOT NULL DEFAULT 'pending_payment', \`total_amount\` decimal(10,2) NOT NULL, \`cancellation_reason\` text NULL, \`cancelled_at\` datetime NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`requester_user_id\` varchar(36) NULL, \`mass_request_type_id\` int NULL, \`mass_calendar_id\` int NULL, \`payment_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`mass_request_schedules\` (\`id\` int NOT NULL AUTO_INCREMENT, \`scheduled_date\` date NOT NULL, \`status\` enum ('scheduled', 'celebrated', 'transferred') NOT NULL DEFAULT 'scheduled', \`transfer_to_mass_id\` int NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`mass_request_id\` int NULL, \`mass_calendar_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`mass_request_packages\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`amount\` decimal(10,2) NOT NULL, \`valid_from\` date NULL, \`valid_until\` date NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`mass_request_type_id\` int NULL, \`applies_to_mass_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`mass_request_details\` (\`id\` int NOT NULL AUTO_INCREMENT, \`detail_type\` varchar(100) NOT NULL, \`value\` text NOT NULL, \`mass_request_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`contribution_campaigns\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`start_date\` date NOT NULL, \`end_date\` date NULL, \`is_fixed_amount\` tinyint NOT NULL DEFAULT 0, \`fixed_amount\` decimal(10,2) NULL, \`target_group\` enum ('all', 'adults', 'youth', 'families', 'specific') NOT NULL DEFAULT 'all', \`target_participant_count\` int NULL, \`target_amount\` decimal(12,2) NULL, \`minimum_individual_amount\` decimal(10,2) NULL, \`status\` enum ('active', 'inactive', 'completed') NOT NULL DEFAULT 'active', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by_user_id\` varchar(36) NULL, INDEX \`idx_campaign_status\` (\`status\`), UNIQUE INDEX \`IDX_eac55b2b0d8f51c082a01e643b\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`contributions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`amount\` decimal(10,2) NOT NULL, \`contribution_method\` enum ('online', 'cash_on_site') NOT NULL, \`contribution_date\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, \`notes\` text NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`card_id\` varchar(36) NULL, \`contributor_user_id\` varchar(36) NULL, \`payment_id\` int NULL, \`collected_by_user_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`contribution_cards\` (\`id\` varchar(36) NOT NULL, \`card_number\` varchar(50) NOT NULL, \`phone_number\` varchar(20) NULL, \`initial_amount\` decimal(10,2) NOT NULL DEFAULT '0.00', \`current_balance\` decimal(10,2) NOT NULL DEFAULT '0.00', \`qr_code_url\` varchar(255) NULL, \`is_physical\` tinyint NOT NULL DEFAULT 0, \`status\` enum ('active', 'inactive', 'completed', 'suspended') NOT NULL DEFAULT 'active', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`campaign_id\` int NULL, \`user_id\` varchar(36) NULL, INDEX \`idx_card_phone\` (\`phone_number\`), INDEX \`idx_card_campaign\` (\`campaign_id\`), INDEX \`idx_card_user\` (\`user_id\`), INDEX \`idx_card_number\` (\`card_number\`), UNIQUE INDEX \`IDX_d4564e835569b9cf738e71d033\` (\`card_number\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`user_has_roles\` ADD CONSTRAINT \`FK_d2b980baf026ff8347d88ace6ee\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_has_roles\` ADD CONSTRAINT \`FK_386dc0042695c976845d36be948\` FOREIGN KEY (\`role_id\`) REFERENCES \`user_roles\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reports\` ADD CONSTRAINT \`FK_ca7a21eb95ca4625bd5eaef7e0c\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reports\` ADD CONSTRAINT \`FK_2175e422a1746cc833c83931386\` FOREIGN KEY (\`report_config_id\`) REFERENCES \`reports_config\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transactions\` ADD CONSTRAINT \`FK_e9acc6efa76de013e8c1553ed2b\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transactions\` ADD CONSTRAINT \`FK_ffaf391d65e368f230841b0a3b6\` FOREIGN KEY (\`payment_gateway_id\`) REFERENCES \`payment_gateways\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`offerings\` ADD CONSTRAINT \`FK_c7f903facbda6a909db123f38bb\` FOREIGN KEY (\`offering_type_id\`) REFERENCES \`offering_types\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`offerings\` ADD CONSTRAINT \`FK_1f99028fdad8920ebf5bd4be8b7\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`offerings\` ADD CONSTRAINT \`FK_c52a5a78fea96a78fa0482f286c\` FOREIGN KEY (\`campaign_id\`) REFERENCES \`offering_campaigns\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mass_calendar\` ADD CONSTRAINT \`FK_7e98ffebabda1a137b2286fe98e\` FOREIGN KEY (\`celebration_type_id\`) REFERENCES \`celebration_types\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mass_requests\` ADD CONSTRAINT \`FK_9fd9e5476e5a8476236da377beb\` FOREIGN KEY (\`requester_user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mass_requests\` ADD CONSTRAINT \`FK_5c7178d07ba14b99d8961d80a01\` FOREIGN KEY (\`mass_request_type_id\`) REFERENCES \`mass_request_types\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mass_requests\` ADD CONSTRAINT \`FK_13f406976bfe757569f77b937e1\` FOREIGN KEY (\`mass_calendar_id\`) REFERENCES \`mass_calendar\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mass_requests\` ADD CONSTRAINT \`FK_6a161cb797ce83a0f74630ca5bc\` FOREIGN KEY (\`payment_id\`) REFERENCES \`transactions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mass_request_schedules\` ADD CONSTRAINT \`FK_6e1cb22ae23e98cef6e39c06a5e\` FOREIGN KEY (\`mass_request_id\`) REFERENCES \`mass_requests\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mass_request_schedules\` ADD CONSTRAINT \`FK_f524eff9cc21c0cc4f5aff168b0\` FOREIGN KEY (\`mass_calendar_id\`) REFERENCES \`mass_calendar\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mass_request_packages\` ADD CONSTRAINT \`FK_ad314dbdee4067752c121a73816\` FOREIGN KEY (\`mass_request_type_id\`) REFERENCES \`mass_request_types\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mass_request_packages\` ADD CONSTRAINT \`FK_e538ddc019ad2f91614e56256b1\` FOREIGN KEY (\`applies_to_mass_id\`) REFERENCES \`mass_calendar\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mass_request_details\` ADD CONSTRAINT \`FK_1e5064075269f85769478701cc8\` FOREIGN KEY (\`mass_request_id\`) REFERENCES \`mass_requests\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contribution_campaigns\` ADD CONSTRAINT \`FK_cf78c9b87da46ce28c2fb886d9d\` FOREIGN KEY (\`created_by_user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contributions\` ADD CONSTRAINT \`FK_c123fe39f21f890def663a61a4f\` FOREIGN KEY (\`card_id\`) REFERENCES \`contribution_cards\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contributions\` ADD CONSTRAINT \`FK_3f2b2aad01ed2e594704159d6c7\` FOREIGN KEY (\`contributor_user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contributions\` ADD CONSTRAINT \`FK_38773f7261a36a7efb77cf6ae2c\` FOREIGN KEY (\`payment_id\`) REFERENCES \`transactions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contributions\` ADD CONSTRAINT \`FK_6a1debd645fbdaec9df1176e67a\` FOREIGN KEY (\`collected_by_user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contribution_cards\` ADD CONSTRAINT \`FK_8e3ee3770f891f502fa8b3de02f\` FOREIGN KEY (\`campaign_id\`) REFERENCES \`contribution_campaigns\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contribution_cards\` ADD CONSTRAINT \`FK_821548f0cb2aedbd8f1040e0fdd\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`contribution_cards\` DROP FOREIGN KEY \`FK_821548f0cb2aedbd8f1040e0fdd\``);
        await queryRunner.query(`ALTER TABLE \`contribution_cards\` DROP FOREIGN KEY \`FK_8e3ee3770f891f502fa8b3de02f\``);
        await queryRunner.query(`ALTER TABLE \`contributions\` DROP FOREIGN KEY \`FK_6a1debd645fbdaec9df1176e67a\``);
        await queryRunner.query(`ALTER TABLE \`contributions\` DROP FOREIGN KEY \`FK_38773f7261a36a7efb77cf6ae2c\``);
        await queryRunner.query(`ALTER TABLE \`contributions\` DROP FOREIGN KEY \`FK_3f2b2aad01ed2e594704159d6c7\``);
        await queryRunner.query(`ALTER TABLE \`contributions\` DROP FOREIGN KEY \`FK_c123fe39f21f890def663a61a4f\``);
        await queryRunner.query(`ALTER TABLE \`contribution_campaigns\` DROP FOREIGN KEY \`FK_cf78c9b87da46ce28c2fb886d9d\``);
        await queryRunner.query(`ALTER TABLE \`mass_request_details\` DROP FOREIGN KEY \`FK_1e5064075269f85769478701cc8\``);
        await queryRunner.query(`ALTER TABLE \`mass_request_packages\` DROP FOREIGN KEY \`FK_e538ddc019ad2f91614e56256b1\``);
        await queryRunner.query(`ALTER TABLE \`mass_request_packages\` DROP FOREIGN KEY \`FK_ad314dbdee4067752c121a73816\``);
        await queryRunner.query(`ALTER TABLE \`mass_request_schedules\` DROP FOREIGN KEY \`FK_f524eff9cc21c0cc4f5aff168b0\``);
        await queryRunner.query(`ALTER TABLE \`mass_request_schedules\` DROP FOREIGN KEY \`FK_6e1cb22ae23e98cef6e39c06a5e\``);
        await queryRunner.query(`ALTER TABLE \`mass_requests\` DROP FOREIGN KEY \`FK_6a161cb797ce83a0f74630ca5bc\``);
        await queryRunner.query(`ALTER TABLE \`mass_requests\` DROP FOREIGN KEY \`FK_13f406976bfe757569f77b937e1\``);
        await queryRunner.query(`ALTER TABLE \`mass_requests\` DROP FOREIGN KEY \`FK_5c7178d07ba14b99d8961d80a01\``);
        await queryRunner.query(`ALTER TABLE \`mass_requests\` DROP FOREIGN KEY \`FK_9fd9e5476e5a8476236da377beb\``);
        await queryRunner.query(`ALTER TABLE \`mass_calendar\` DROP FOREIGN KEY \`FK_7e98ffebabda1a137b2286fe98e\``);
        await queryRunner.query(`ALTER TABLE \`offerings\` DROP FOREIGN KEY \`FK_c52a5a78fea96a78fa0482f286c\``);
        await queryRunner.query(`ALTER TABLE \`offerings\` DROP FOREIGN KEY \`FK_1f99028fdad8920ebf5bd4be8b7\``);
        await queryRunner.query(`ALTER TABLE \`offerings\` DROP FOREIGN KEY \`FK_c7f903facbda6a909db123f38bb\``);
        await queryRunner.query(`ALTER TABLE \`transactions\` DROP FOREIGN KEY \`FK_ffaf391d65e368f230841b0a3b6\``);
        await queryRunner.query(`ALTER TABLE \`transactions\` DROP FOREIGN KEY \`FK_e9acc6efa76de013e8c1553ed2b\``);
        await queryRunner.query(`ALTER TABLE \`reports\` DROP FOREIGN KEY \`FK_2175e422a1746cc833c83931386\``);
        await queryRunner.query(`ALTER TABLE \`reports\` DROP FOREIGN KEY \`FK_ca7a21eb95ca4625bd5eaef7e0c\``);
        await queryRunner.query(`ALTER TABLE \`user_has_roles\` DROP FOREIGN KEY \`FK_386dc0042695c976845d36be948\``);
        await queryRunner.query(`ALTER TABLE \`user_has_roles\` DROP FOREIGN KEY \`FK_d2b980baf026ff8347d88ace6ee\``);
        await queryRunner.query(`DROP INDEX \`IDX_d4564e835569b9cf738e71d033\` ON \`contribution_cards\``);
        await queryRunner.query(`DROP INDEX \`idx_card_number\` ON \`contribution_cards\``);
        await queryRunner.query(`DROP INDEX \`idx_card_user\` ON \`contribution_cards\``);
        await queryRunner.query(`DROP INDEX \`idx_card_campaign\` ON \`contribution_cards\``);
        await queryRunner.query(`DROP INDEX \`idx_card_phone\` ON \`contribution_cards\``);
        await queryRunner.query(`DROP TABLE \`contribution_cards\``);
        await queryRunner.query(`DROP TABLE \`contributions\``);
        await queryRunner.query(`DROP INDEX \`IDX_eac55b2b0d8f51c082a01e643b\` ON \`contribution_campaigns\``);
        await queryRunner.query(`DROP INDEX \`idx_campaign_status\` ON \`contribution_campaigns\``);
        await queryRunner.query(`DROP TABLE \`contribution_campaigns\``);
        await queryRunner.query(`DROP TABLE \`mass_request_details\``);
        await queryRunner.query(`DROP TABLE \`mass_request_packages\``);
        await queryRunner.query(`DROP TABLE \`mass_request_schedules\``);
        await queryRunner.query(`DROP TABLE \`mass_requests\``);
        await queryRunner.query(`DROP INDEX \`IDX_3819838db5da5f8c44f1304f39\` ON \`mass_request_types\``);
        await queryRunner.query(`DROP TABLE \`mass_request_types\``);
        await queryRunner.query(`DROP TABLE \`mass_calendar\``);
        await queryRunner.query(`DROP INDEX \`IDX_70cfa0b4b38261bd5cc6350edb\` ON \`celebration_types\``);
        await queryRunner.query(`DROP TABLE \`celebration_types\``);
        await queryRunner.query(`DROP INDEX \`idx_offering_date\` ON \`offerings\``);
        await queryRunner.query(`DROP INDEX \`idx_offering_amount\` ON \`offerings\``);
        await queryRunner.query(`DROP INDEX \`idx_offering_status\` ON \`offerings\``);
        await queryRunner.query(`DROP TABLE \`offerings\``);
        await queryRunner.query(`DROP INDEX \`idx_campaign_dates\` ON \`offering_campaigns\``);
        await queryRunner.query(`DROP INDEX \`idx_campaign_status\` ON \`offering_campaigns\``);
        await queryRunner.query(`DROP TABLE \`offering_campaigns\``);
        await queryRunner.query(`DROP INDEX \`IDX_2ba25d9c762806798d33170e65\` ON \`offering_types\``);
        await queryRunner.query(`DROP TABLE \`offering_types\``);
        await queryRunner.query(`DROP INDEX \`IDX_0c5bb9849cf031ff303e84203b\` ON \`parishes\``);
        await queryRunner.query(`DROP INDEX \`idx_parish_name\` ON \`parishes\``);
        await queryRunner.query(`DROP TABLE \`parishes\``);
        await queryRunner.query(`DROP INDEX \`IDX_dd85cc865e0c3d5d4be095d3f3\` ON \`transactions\``);
        await queryRunner.query(`DROP TABLE \`transactions\``);
        await queryRunner.query(`DROP INDEX \`IDX_d905f911f872997feb55664dd7\` ON \`payment_gateways\``);
        await queryRunner.query(`DROP TABLE \`payment_gateways\``);
        await queryRunner.query(`DROP TABLE \`reports\``);
        await queryRunner.query(`DROP INDEX \`IDX_4d0462a12befd82c5979ae17fa\` ON \`reports_config\``);
        await queryRunner.query(`DROP TABLE \`reports_config\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP TABLE \`user_has_roles\``);
        await queryRunner.query(`DROP INDEX \`IDX_4a77d431a6b2ac981c342b13c9\` ON \`user_roles\``);
        await queryRunner.query(`DROP TABLE \`user_roles\``);
        await queryRunner.query(`DROP TABLE \`password_resets\``);
    }

}
